### ISSUE TITLE
Project bootstrapping

### ISSUE THREAD

**Issue by kingscott** [CivicTechWR/improved_housing_portal#1]
## TODO
- [x] Create a new project
- [x] Give your project a name
- [x] Create the slack channel named #project_[project name]
- [x] Edit your GitHub repo's readme to tell your story
- [ ] Define your tooling & write a getting started guide for your tech stack
- [x] Update the slack channel topic to link to your GitHub repo's readme
- [ ] Define some project milestones (eg: Proof of Concept, Minimum Testable Product, Minimum Useful Product)
- [ ] Give your project milestones some dates
- [ ] Tell the #organizing channel when you want to run your first show & tell
- [ ] Share an update about the project in #general & invite people to join your team!
